When TerraformBoot enables authentication, Xpanse calls its APIs alwa…
eclipse-xpanse/xpanse pull request #1081
Opened 2023-11-30 09:54 UTC by WangLiNaruto

Fixed #1043
related to https://github.com/eclipse-xpanse/terraform-boot/pull/37

![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/7f67ead9-561a-4175-aade-2f4d0acdbcd9)
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/33de62f6-9ede-4227-88c2-d664e7daf4ef)

![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/1d67b22d-afaa-43d8-8f22-dfe53c5c52d4)
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/aa6e5d74-3c8b-4104-a493-7f3c884b8ec2)

2023-11-30 11:32 UTC, baixinsui requested changes
Some comment need to check

2023-11-30 11:32 UTC, baixinsui commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/security/model/CurrentUserInfoCacheHolder.java
> +    private static final Map<String, CurrentUserInfo> USERINFO_CACHE
Using this solution, the map seems always store only the latest putted user . Please test if the user information obtained in the sub thread is correct if multiple users access it simultaneously. If not correct, you can try to use the `ThreadLocal<CurrentUserInfo>` to obtain the user information in sub threads.

2023-11-30 11:32 UTC, baixinsui commented on modules/security/src/main/java/org/eclipse/xpanse/modules/security/zitadel/ZitadelIdentityProviderService.java
> +            CurrentUserInfoCacheHolder.getSingleton().setCurrentUserInfo(currentUserInfo);
If current solution using `ConcurrentHashMap` works well,  please move the set action to `IdentityProviderManager`. If change to use the new solution `ConcurrentHashMap`, delete the set acition.

2023-11-30 11:32 UTC, baixinsui commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/security/model/CurrentUserInfoCacheHolder.java
> +
The initial capacity of map is `0`?

2023-12-01 09:31 UTC, baixinsui approved these changes
LGTM

2023-12-01 10:33 UTC, swaroopar requested changes

2023-12-01 10:33 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/security/model/CurrentUserInfoHolder.java
> +@Profile("zitadel")
do we need this profile annotation as this class is not a spring bean?

please also consider that if Zitdel profile is not enabled .. then there is no token available. So in this case, no auth header must be sent.

2023-12-04 05:14 UTC, swaroopar approved these changes
LGTM

2023-12-04 05:14 UTC, merged