remove async threads when terraform-boot is activated
eclipse-xpanse/xpanse pull request #1198
Opened 2023-12-26 06:43 UTC by WangLiNaruto

Fixed #1078
![image](https://github.com/eclipse-xpanse/xpanse/assets/122504203/17e772f1-913c-4ad9-8540-62ffad939b4f)

2023-12-26 09:45 UTC, swaroopar requested changes

2023-12-26 09:45 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> -    public void deployCallback(String taskId, TerraformResult result) {
we need this one too. There is no change expected here.

2023-12-26 09:45 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/WebhookApi.java
> -/*
we need these methods still.

2023-12-30 15:10 UTC, swaroopar requested changes
this looks definitely good. 
There are also 3 more places in this class where we have @async annotated method. can we get rid of them too please?

2024-01-02 01:37 UTC, WangLiNaruto commented
> this looks definitely good. There are also 3 more places in this class where we have @async annotated method. can we get rid of them too please?


Sure, the other @Async methods I saw are about purge or migrate. Don’t they need to be executed asynchronously? If asynchronous is not needed, I feel like I should submit a new PR.

2024-01-02 05:37 UTC, swaroopar commented
> > this looks definitely good. There are also 3 more places in this class where we have @async annotated method. can we get rid of them too please?
> 
> Sure, the other @async methods I saw are about purge or migrate. Don’t they need to be executed asynchronously? If asynchronous is not needed, I feel like I should submit a new PR.

@WangLiNaruto yes, even purge and migrate must work similar to deploy and destroy. We must start async step only in the terraform-local

2024-01-02 05:51 UTC, swaroopar approved these changes
LGTM

2024-01-02 05:51 UTC, merged