Check schema of variables in templates and validate input variables
eclipse-xpanse/xpanse pull request #1463
Opened 2024-03-14 06:32 UTC by baixinsui

fixes https://github.com/eclipse-xpanse/xpanse/issues/1462
Register service template with duplicated deploy variable name:

2024-03-19 01:22 UTC, swaroopar requested changes

2024-03-19 02:35 UTC, baixinsui commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaValidator.java
> +            Set<ValidationMessage> validate = schema.validate(jsonNode);
@swaroopar This validate method was unable to verify required properties. 
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/fa90a5b7-e1a6-4da5-b8ec-e16e115a90cb)
When the required property `admin_passwd` is missing, the deploy task will be created not thrown exception. 
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/9716981a-94b3-408b-925e-39d8ae7ecc62)
Then the deploy task failed by required variable not set.
![image](https://github.com/eclipse-xpanse/xpanse/assets/121531362/68ec1b15-ddcf-427a-9680-3a811ce6db02)
I think this type of error should be thrown before generating the new task, So I added additional verification logic.

2024-03-20 01:32 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaValidator.java
> +            Set<ValidationMessage> validate = schema.validate(jsonNode);
@baixinsui this is definitely a bug. Then there is an issue in generating our JSON Schema file. 
The idea was that the json schema what we write automatically validates the required fields. We should not do any other extra validation. Would be great if you can check why this schema validation not working. 

ServiceVariablesJsonSchemaGenerator:77

2024-03-20 01:35 UTC, baixinsui commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaValidator.java
> +            Set<ValidationMessage> validate = schema.validate(jsonNode);
Ok. I will check it.

2024-03-20 07:58 UTC, baixinsui commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/service/utils/ServiceVariablesJsonSchemaValidator.java
> +            Set<ValidationMessage> validate = schema.validate(jsonNode);
@swaroopar Fixed the error validation with JSON Schema.

2024-03-27 06:13 UTC, closed without merging