Add spring retry for third-party service calls
eclipse-xpanse/xpanse pull request #1644
Opened 2024-05-27 08:09 UTC by baixinsui

fixes https://github.com/eclipse-xpanse/xpanse/issues/1630

2024-05-27 13:37 UTC, swaroopar requested changes

2024-05-27 13:37 UTC, swaroopar commented on runtime/src/main/resources/application.properties
> +spring.retry.max-attempts=5
pls rename this to http.request.retry.max.attempts

2024-05-27 13:37 UTC, swaroopar commented on runtime/src/main/resources/application.properties
> +spring.retry.delay-millions=1000
rename this to http.request.retry.delay.milliseconds

2024-05-28 01:50 UTC, Alice1319 commented
LGTM

2024-05-28 04:27 UTC, swaroopar approved these changes
LGTM

2024-05-28 06:55 UTC, merged