replace generic ID fields to more specific names
eclipse-xpanse/xpanse pull request #1688
Opened 2024-06-05 03:39 UTC by WangLiNaruto

Fixed #1648

2024-06-05 09:27 UTC, baixinsui commented
LGTM

2024-06-06 03:17 UTC, swaroopar requested changes

2024-06-06 03:17 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/migration/steps/StartDeploy.java
> +        deployRequest.setId(migrateRequest.getOriginalServiceId());
we can update the Id filed in DeployRequest also as 'ServiceId'

2024-06-06 03:17 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/config/ServiceTemplateEntityConverter.java
> +            serviceTemplateDetailVo.setServiceTemplateId(serviceTemplateEntity.getId());
Does it make sense to also to rename the ID field in the entities?

2024-06-06 07:33 UTC, Alice1319 commented
LGTM

2024-06-06 07:55 UTC, swaroopar approved these changes
LGTM

2024-06-06 07:55 UTC, merged