handle multiple cloud providers based on same cloud implementation
eclipse-xpanse/xpanse pull request #1725
Opened 2024-06-20 10:07 UTC by baixinsui

fixes #1709

2024-06-21 07:59 UTC, baixinsui commented
@swaroopar 
I have only completed code refactoring and have not tested it yet. Could you please take a look at what needs to be modified first.

2024-06-23 03:56 UTC, swaroopar requested changes

2024-06-23 03:56 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/utils/DeployEnvironments.java
> +    private void setProviderOsAuthUrl(Csp csp, Map<String, String> variables) {
this logic must be part of plugin of each cloud provider.
the Orchestrator must only ask the corresponding plugin for these variables and the translation must come from it.

2024-06-23 03:56 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/enums/Csp.java
> +    AMAZON_CLOUD("AmazonCloud"),
this should be just `aws`

2024-06-23 03:56 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/enums/Csp.java
> +    GOOGLE_CLOUD("GoogleCloud");
this should be `GCP("GoogleCloudPlatform")`

2024-06-23 03:56 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/common/enums/Csp.java
> +    AZURE_CLOUD("AzureCloud"),
this should be just `azure`

2024-06-23 03:56 UTC, swaroopar commented on modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/PluginManager.java
> +            if (Objects.nonNull(osAuthUrl)) {
The logic here is fine. But we need another way to get the list of of "black listed" environment variables. 
We can have this is a list in properties file.

2024-06-23 03:56 UTC, swaroopar commented on plugins/common/src/main/java/org/eclipse/xpanse/plugins/common/opensatckcommon/auth/ProviderAuthInfoResolver.java
> +package org.eclipse.xpanse.plugins.common.opensatckcommon.auth;
package name can be just - openstack

2024-06-23 03:56 UTC, swaroopar commented on plugins/huawei-cloud/pom.xml
> +    <artifactId>huawei-cloud</artifactId>
we must keep the old name itself.  same applies for flexibleengine, regiocloud, plusserver.. they are all just one single word

2024-06-25 10:22 UTC, swaroopar requested changes

2024-06-26 07:05 UTC, swaroopar approved these changes
LGTM

2024-06-26 07:06 UTC, merged