Add a area level for regions
eclipse-xpanse/xpanse pull request #198
Opened 2023-03-15 08:00 UTC by WangLiNaruto

[#181 ](url)

2023-03-15 08:02 UTC, iskey commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/resource/Area.java
> +    @Schema(description = "The name of the area")
Also, adding @NotBlank is better?

2023-03-15 08:04 UTC, iskey commented
Please fix all the OCL examples with the same.

2023-03-17 09:03 UTC, davidinux commented
@WangLiNaruto it appears you haven't either completed ECA process or using an email that is not linked to your Eclipse Foundation contributor profile, hence the merge is flagged as blocked.

2023-03-17 09:05 UTC, davidinux approved these changes
LGTM

2023-03-20 00:46 UTC, niuzhenguo commented
All contributors must sign the ECA, pls follow this https://www.eclipse.org/projects/handbook/#contributing-eca

2023-03-20 04:55 UTC, iskey requested changes
Please fix all the examples.

2023-03-24 07:15 UTC, iskey commented
As we decide to make the `area` a field of the `Region`, as #210 does, I am going to close this PR now.

2023-03-24 07:15 UTC, closed without merging