add recreate.
eclipse-xpanse/xpanse pull request #1985
Opened 2024-09-27 12:11 UTC by Alice1319

fixes #1916

2024-09-29 01:11 UTC, WangLiNaruto commented
LGTM

2024-09-30 04:45 UTC, swaroopar requested changes

2024-09-30 04:45 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    @Tag(name = "Recreate", description = "APIs to manage the service recreate.")
we do not need a new tag here. The tag and description must be same as 

@Tag(name = "Service", description = "APIs to manage the services")

2024-09-30 04:45 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    public UUID recreateService(@Valid @RequestBody RecreateRequest recreateRequest) {
Also there should be no request body here. The recreate will just use whatever parameters that was used to deploy the service.

2024-09-30 04:45 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    @PostMapping(value = "/services/recreate", produces = MediaType.APPLICATION_JSON_VALUE)
should be PUT with serviceId in the URI.

2024-09-30 04:45 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/recreate/steps/ProcessRecreateDeploymentResult.java
> +                processInstanceId, originalServiceId.toString());
i have not checked this in detail. But pls ensure that the same entry in DEPLOY_SERVICE table is used to destroy and also deploy again.

2024-09-30 08:37 UTC, Alice1319 commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    public UUID recreateService(@Valid @RequestBody RecreateRequest recreateRequest) {
we will fix this one at another userstory.

2024-10-08 10:11 UTC, swaroopar requested changes

2024-10-08 10:11 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    @AuditApiRequest(methodName = "getCspFromRequestUri")
this must be `@AuditApiRequest(methodName = "getCspFromServiceId")`

2024-10-08 10:11 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/controllers/ServiceRecreateApi.java
> +    @AuditApiRequest(methodName = "getCspFromServiceRecreateId")
where is this method 'getCspFromServiceRecreateId' created?

2024-10-08 12:23 UTC, swaroopar approved these changes
LGTM

2024-10-08 12:23 UTC, merged