make SERVICE_ID column as FK in SERVICE_ORDER table
eclipse-xpanse/xpanse pull request #2019
Opened 2024-10-10 02:20 UTC by WangLiNaruto

Fixed #1977 
![image](https://github.com/user-attachments/assets/259c8208-02ca-4ac9-9fe6-7f1f45e20701)

2024-10-10 02:45 UTC, baixinsui commented
LGTM

2024-10-15 08:26 UTC, swaroopar requested changes

2024-10-15 08:26 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
> +        query.setDeployServiceEntity(deployServiceStorage.findDeployServiceById(serviceId));
do we really need to set the full object in query?
probably it is enough to set `query.setServiceId(deployServiceStorage.findDeployServiceById(serviceId).getId());`

2024-10-15 08:26 UTC, swaroopar commented on modules/database/src/main/java/org/eclipse/xpanse/modules/database/serviceorder/DatabaseServiceOrderStorage.java
> +                                entity.getDeployServiceEntity()));
same here. Query should be based on same Id. not the complete entity.

2024-10-16 07:53 UTC, baixinsui reviewed
are these modified tables available in both the H2 and MySQL databases? This is important.

2024-10-17 08:59 UTC, swaroopar approved these changes
LGTM

2024-10-17 08:59 UTC, merged