Generate API clients for tofu-maker and terraform-boot
eclipse-xpanse/xpanse pull request #2034
Opened 2024-10-14 03:52 UTC by baixinsui

Fixed https://github.com/eclipse-xpanse/xpanse/issues/1943

2024-10-14 03:53 UTC, baixinsui commented
Waiting tests already

2024-10-14 12:21 UTC, swaroopar requested changes

2024-10-14 12:21 UTC, swaroopar commented on modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployResult.java
> +    private String deployerWithVersion;
deployerVersionUsed

2024-10-14 12:21 UTC, swaroopar commented on modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeploymentScriptValidationResult.java
> +    private String deployerWithVersion;
this must be 'deployerVersionUsed'

2024-10-15 01:18 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/deployertools/DeployerToolUtils.java
> +        return isVersionSatisfied(versionNumber, requiredOperator, requiredNumber);
This method will be called in method for find best version in installed executors and the method for installing best version into the installation path. It is useful for the first case, but unnecessary for the second case. I will create a new method for the second case without `isVersionSatisified`.

2024-10-15 02:05 UTC, Alice1319 commented
LGTM

2024-10-15 09:56 UTC, swaroopar approved these changes
LGTM

2024-10-15 09:56 UTC, merged