Track service managements(deploy/modify/destroy/rollback/retry/purge) into table service_order
eclipse-xpanse/xpanse pull request #2047
Opened 2024-10-18 02:51 UTC by baixinsui

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2031

Deploy service successfully:
![chrome_e7CeYGNVsf](https://github.com/user-attachments/assets/7857b620-755c-4271-8111-2d4ba44e216e)

Modify service successfuuly:

Deploy service failed:
![image](https://github.com/user-attachments/assets/769adb2a-f3d4-4369-8afc-986ac65ebbc6)

2024-10-18 05:03 UTC, swaroopar requested changes

2024-10-18 06:20 UTC, Alice1319 commented
LGTM

2024-10-18 06:24 UTC, WangLiNaruto commented
LGTM

2024-10-18 06:57 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
>              serviceOrderManager.startOrderProgress(deployTask.getOrderId());
sure. The new service always be created and stored.

2024-10-18 06:57 UTC, baixinsui commented on modules/orchestrator/src/main/java/org/eclipse/xpanse/modules/orchestrator/deployment/DeployResult.java
>      private UUID serviceId;
Deleted.

2024-10-18 08:27 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceOrderManager.java
> +        if (deployTask.getTaskType() == ServiceOrderType.DEPLOY) {
deleted

2024-10-18 09:16 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
> +        ServiceOrderEntity entityToUpdate = new ServiceOrderEntity();
The previous properties stored into the service_order table when every order entity created, and the new properties after task stored in the table deploy_service. No properties need to update into parent order.

2024-10-23 03:18 UTC, WangLiNaruto commented
LGTM

2024-10-23 06:20 UTC, merged