Query service template history and query request ocl by changeId
eclipse-xpanse/xpanse pull request #2164
Opened 2024-12-03 09:13 UTC by baixinsui

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2106

2024-12-03 11:12 UTC, Alice1319 commented
LGTM

2024-12-03 11:18 UTC, wuzhuanhong commented
LGTM

2024-12-03 11:19 UTC, profoundwu commented
LGTM

2024-12-03 11:19 UTC, luoping-12345 commented
LGTM

2024-12-03 11:25 UTC, dengyali0125 commented
LGTM

2024-12-03 14:03 UTC, swaroopar requested changes

2024-12-03 14:03 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplatechange/ServiceTemplateHistoryVo.java
> +package org.eclipse.xpanse.modules.models.servicetemplatechange;
how about moving 'change' folder insider 'servicetemplate' folder?

2024-12-03 14:03 UTC, swaroopar commented on modules/servicetemplate/src/main/java/org/eclipse/xpanse/modules/servicetemplate/ServiceTemplateManage.java
> +                .sorted(Comparator.comparing(ServiceTemplateHistoryEntity::getCreateTime)
this is good. can we also write this in the API doc - the history returned is sorted by the ascending order of the change requested time.

2024-12-04 06:29 UTC, swaroopar approved these changes
LGTM

2024-12-04 06:29 UTC, merged