Integrate getStoredTaskResultByRequestId in xpanse
eclipse-xpanse/xpanse pull request #2180
Opened 2024-12-06 03:27 UTC by WangLiNaruto

Fixed #2130

2024-12-06 03:50 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> +            return Handler.INTERNAL;
The activeProfile could not be empty, this case is not right.

2024-12-06 03:53 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> +    }
Or maybe you can set INTERNAL as the default value as the result.

2024-12-06 06:57 UTC, Alice1319 commented
LGTM

2024-12-06 08:17 UTC, yuanxiaojun987 commented
LGTM

2024-12-09 14:21 UTC, swaroopar requested changes

2024-12-09 14:21 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
> +    private void updateServiceDeploymentStateAndServiceOrderByStoredTerraformResult(
refetchDeploymentStateForMissingOrdersFromDeployers

2024-12-09 14:30 UTC, swaroopar requested changes

2024-12-09 14:30 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
> +    private void updateServiceDeploymentStateAndServiceOrderByStoredTerraformResult(
better we move all this new code to a new spring bean.

2024-12-09 14:30 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/ServiceDetailsViewManager.java
> +                        ResponseEntity<TerraformResult> result = terraformBootTaskResultHelper
would prefer if we extract the response object in the terraformBootTaskResultHelper class itself and send the actual response object

2024-12-09 14:30 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/opentofu/tofumaker/TofuMakerTaskResultHelper.java
> +public class TofuMakerTaskResultHelper {
TofuMakerResultRefetchManager

2024-12-09 14:30 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/terraformboot/TerraformBootTaskResultHelper.java
> +public class TerraformBootTaskResultHelper {
TerraformBootResultRefetchManager

2024-12-10 09:11 UTC, swaroopar requested changes

2024-12-10 09:11 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
> +        if (e.getStatusCode() == HttpStatus.BAD_REQUEST
please move all this to corresponding result handlers.

2024-12-10 09:11 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
> +                == Response.ResultTypeEnum.RESULT_ALREADY_RETURNED_OR_REQUEST_ID_INVALID) {
ensure we use the 'Response' class from generated models of deployers.

2024-12-10 09:11 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployResultManager.java
> +            log.error(String.format("Modify service failed. orderId %s, error %s ",
but here we are not modifying anything know?

2024-12-10 12:49 UTC, swaroopar approved these changes
LGTM

2024-12-10 12:49 UTC, merged