change service configuration related data model names to common names
eclipse-xpanse/xpanse pull request #2216
Opened 2024-12-16 09:11 UTC by WangLiNaruto

Fixed #2206

![image](https://github.com/user-attachments/assets/dc38b653-8354-4252-92b3-8c2f6b9f1ba6)
![image](https://github.com/user-attachments/assets/6cda51e1-c528-46f1-93bf-f5664b9c1b7f)

2024-12-16 10:19 UTC, Alice1319 commented
LGTM

2024-12-16 13:29 UTC, swaroopar requested changes
only model names must change. but the field names must remain as before. (as mentioned in the last requirement of the userstory)

2024-12-16 13:29 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/Ocl.java
> +    private ServiceChangeManage serviceChangeManage;
the field name must still be serviceConfigurationManage

2024-12-16 13:29 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeManage.java
> +    private List<ServiceChangeScript> serviceChangeScripts;
same here. the field name must be same as before. Only type must be changed.

2024-12-16 13:29 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/ServiceChangeManage.java
> +    private List<ServiceChangeParameter> serviceChangeParameters;
same here.

2024-12-16 13:29 UTC, swaroopar commented on modules/models/src/main/java/org/eclipse/xpanse/modules/models/servicetemplate/view/ServiceTemplateDetailVo.java
> +    private ServiceChangeManage serviceChangeManage;
same here.

2024-12-17 02:47 UTC, wuzhuanhong commented
LGTM

2024-12-17 03:04 UTC, profoundwu commented
LGTM

2024-12-17 03:07 UTC, baixinsui commented
LGTM

2024-12-17 03:12 UTC, yuanxiaojun987 commented
LGTM

2024-12-17 03:29 UTC, luoping-12345 commented
LGTM

2024-12-17 05:07 UTC, swaroopar approved these changes
LGTM

2024-12-17 05:07 UTC, merged