extend OCL to support service actions.
eclipse-xpanse/xpanse pull request #2221
Opened 2024-12-17 11:59 UTC by WangLiNaruto

Fixed #2207 
![image](https://github.com/user-attachments/assets/3ed96611-6b98-41b7-90b8-0fa8a97f6edf)

2024-12-17 12:27 UTC, Alice1319 commented
LGTM

2024-12-17 12:27 UTC, yuanxiaojun987 commented
LGTM

2024-12-17 13:04 UTC, swaroopar requested changes

2024-12-17 13:07 UTC, swaroopar requested changes

2024-12-18 01:30 UTC, luoping-12345 commented
LGTM

2024-12-18 01:38 UTC, baixinsui commented
LGTM

2024-12-18 05:31 UTC, profoundwu commented
LGTM

2024-12-18 07:55 UTC, swaroopar approved these changes
LGTM

2024-12-18 07:55 UTC, merged