add plugin methods to manage the lifecycle of service templates
eclipse-xpanse/xpanse pull request #2248
Opened 2024-12-27 03:31 UTC by baixinsui

Fixed https://github.com/eclipse-xpanse/xpanse/issues/2226
Register service template with  auto-approved is disabled of `HuaweiCloud`:

Register service template with  auto-approved is enabled of `HuaweiCloud`:

2024-12-30 06:15 UTC, Alice1319 commented
LGTM

2024-12-30 09:11 UTC, profoundwu commented
LGTM

2025-01-01 07:00 UTC, swaroopar requested changes

2025-01-02 03:23 UTC, ruwenqiang123 commented
LGTM

2025-01-02 05:39 UTC, swaroopar approved these changes
LGTM

2025-01-02 05:39 UTC, merged