Redefining packages and interfaces of service,credential,storage,monitor
eclipse-xpanse/xpanse pull request #350
Opened 2023-05-11 08:42 UTC by baixinsui

@iskey

2023-05-11 09:21 UTC, swaroopar commented on modules/orchestrator/src/main/java/org/eclipse/xpanse/orchestrator/storage/DeployResourceStorage.java
> +    interface RegisterServiceStorage {
Do we really need such a nested interface?

2023-05-11 09:26 UTC, swaroopar requested changes
package separation looks good. 
Only question about nested interfaces

2023-05-11 12:15 UTC, swaroopar approved these changes
@baixinsui looks fine for me. If Yichao has no further comments, we can merge it.

2023-05-12 01:47 UTC, iskey approved these changes
looks good

2023-05-12 01:48 UTC, merged