add unit tests for the monitor api and credential manage api
eclipse-xpanse/xpanse pull request #371
Opened 2023-05-24 10:11 UTC by wanglin100

2023-05-24 13:18 UTC, swaroopar commented on runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
> +        // Verify the results
assertions missing?

2023-05-24 13:19 UTC, swaroopar requested changes
comment added

2023-05-25 00:40 UTC, wanglin100 commented on runtime/src/test/java/org/eclipse/xpanse/runtime/CredentialManageApiTest.java
> +        // Verify the results
I have modified

2023-05-25 04:50 UTC, swaroopar approved these changes
looks good.

2023-05-25 04:50 UTC, merged