FlexibleEngine batch query Monitor Metric
eclipse-xpanse/xpanse pull request #413
Opened 2023-06-07 08:26 UTC by WangLiNaruto

2023-06-07 09:32 UTC, swaroopar commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +            if (!CollectionUtils.isEmpty(metrics)) {
please move the cache steps to a private method. otherwise the method is simply too long.

2023-06-07 09:33 UTC, swaroopar commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +        List<Metric> metrics = new ArrayList<>();
no need to declare the list here. It can be directly done in the converter.

2023-06-07 09:33 UTC, swaroopar requested changes
comments added.

2023-06-08 06:55 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +            log.error("Build Get Request of the FlexibleEngine API error.", e);
```suggestion
            log.error("Build Get Request of the FlexibleEngine API error.", e);
            log.error("Build Post Request of the FlexibleEngine API error.", e);
```

2023-06-08 07:01 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +        } catch (RestClientException e) {
```suggestion
                } catch (RestClientException | JsonProcessingException e) {
            log.error("batch query metrics list info by url:{} error.", url, e);
        } 
```

2023-06-08 07:01 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +        } catch (JsonProcessingException e) {
```suggestion
        } catch (JsonProcessingException e) {
```

2023-06-08 07:02 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +        } catch (JsonProcessingException e) {
```suggestion
```

2023-06-08 07:03 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +            e.printStackTrace();
```suggestion
```

2023-06-08 07:03 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +        } catch (RestClientException e) {
```suggestion
        } catch (RestClientException | JsonProcessingException e) {
```

2023-06-08 07:04 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +            log.error("query metrics list info by url:{} error.", url, e);
```suggestion
            log.error("batch query metrics list info by url:{} error.", url, e);
```

2023-06-08 07:05 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/MetricsService.java
> +            return null;
```suggestion
            return new ArrayList<>();
```

2023-06-08 08:45 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java
> +                            if (metricInfoList.getUnit().equals("%")) {
In addition to%, other units also need to be set.

2023-06-08 08:45 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/orchestrator/plugin/flexibleengine/monitor/utils/FlexibleEngineMonitorConverter.java
> +            } else if (to - from > ONE_MONTH_MILLISECONDS && to - from <= SIX_MONTH_MILLISECONDS) {
```suggestion
            } else {
```

2023-06-09 03:49 UTC, baixinsui approved these changes
LGTM.

2023-06-09 09:05 UTC, swaroopar approved these changes
looks good.

2023-06-09 09:05 UTC, merged