update log output in Systemcmd
eclipse-xpanse/xpanse pull request #516
Opened 2023-06-25 09:06 UTC by baixinsui

fixed #515

2023-06-25 09:55 UTC, baixinsui commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
> +            if (0 == System.currentTimeMillis() % 1000) {
@sonatype-lift ignoreall

2023-06-25 18:32 UTC, swaroopar approved these changes
LGTM

2023-06-25 18:32 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
> +            throw new RuntimeException(e);
We must throw TerraformExecutorException here and avoid throwing any java inbuilt exceptions.

2023-06-25 18:33 UTC, swaroopar requested changes
one minor comment added.

2023-06-26 01:42 UTC, iskey requested changes
some comments added.

2023-06-26 01:42 UTC, iskey commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/utils/SystemCmd.java
> +            if (0 == System.currentTimeMillis() % 1000) {
If we use `System.currentTimeMillis()` here, the expression may always be false during a calling.

2023-06-26 03:26 UTC, swaroopar approved these changes
LGTM

2023-06-26 03:41 UTC, iskey approved these changes
LGTM

2023-06-26 03:41 UTC, merged