add code unit tests for the module plugins/flexibleengine
eclipse-xpanse/xpanse pull request #518
Opened 2023-06-25 11:27 UTC by baixinsui

fixed #517

2023-06-25 18:34 UTC, swaroopar commented on plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/RetryTemplateServiceTest.java
> +    void testQueryMetricData_cpu_usage() throws URISyntaxException {
method names without underscore pls.

2023-06-25 18:35 UTC, swaroopar commented on plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/constant/FlexibleEngineMonitorConstantsTest.java
> +    @BeforeEach
Do we need this empty test?

2023-06-25 18:35 UTC, swaroopar commented on plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/models/FlexibleEngineResourcePropertyTest.java
> +    void testGetVmProperties_VM() {
same here. Method names only regular java style camel case pls.

2023-06-25 18:36 UTC, swaroopar requested changes
added a comment regarding naming format. Rest looks great.

2023-06-26 00:57 UTC, baixinsui commented on plugins/flexibleengine/src/main/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/utils/MetricsService.java
> +        if (Objects.isNull(project) || StringUtils.isBlank(project.getId())) {
@sonatype-lift ignoreall

2023-06-26 02:36 UTC, baixinsui commented on plugins/flexibleengine/src/test/java/org/eclipse/xpanse/plugins/flexibleengine/monitor/constant/FlexibleEngineMonitorConstantsTest.java
> +    @BeforeEach
I removed it.

2023-06-26 03:25 UTC, swaroopar approved these changes
LGTM

2023-06-26 03:25 UTC, merged