Add pbkdf2 encode/decode for credential sensitive field
eclipse-xpanse/xpanse pull request #592
Opened 2023-07-13 11:44 UTC by WangLiNaruto

Fixed #558

2023-07-13 12:55 UTC, swaroopar requested changes
@WangLiNaruto we are only encoding the value and storing. How/where are we handling the decoding?

2023-07-14 00:56 UTC, WangLiNaruto commented
> @WangLiNaruto we are only encoding the value and storing. How/where are we handling the decoding?

@swaroopar Yes, we just encoded sensitive fields and stored

2023-07-14 01:02 UTC, WangLiNaruto commented
> @WangLiNaruto we are only encoding the value and storing. How/where are we handling the decoding?

2023-07-14 01:02 UTC, closed without merging

2023-07-14 01:18 UTC, baixinsui commented on modules/credential/src/main/java/org/eclipse/xpanse/modules/credential/CredentialCenter.java
> +                variable.setValue(passwordEncoder.encode(variable.getValue()));
When variable.getValue() is null, encode (null) will throw NullPointerException，We should add a judgment condition Objects.isNull(variable.getValue()) ;