implement terraform deployer using terraform-boot API
eclipse-xpanse/xpanse pull request #796
Opened 2023-08-24 08:33 UTC by WangLiNaruto

Fixed eclipse-xpanse/xpanse#758
Fixed eclipse-xpanse/xpanse#759

2023-08-24 09:17 UTC, swaroopar requested changes
@WangLiNaruto i'm a little confused now. Where are we exactly using the client which YangYang generated in this?

2023-08-24 09:20 UTC, swaroopar commented on modules/api/src/main/java/org/eclipse/xpanse/api/ServiceDeployV2Api.java
> +public class ServiceDeployV2Api {
we need to use the same existing APIs. and based on the profile.. we must be able to switch between different terraform deployment. 
Please note that even this profile based selection is also only temporary. Once we have terraform-boot fully working, we will move to that completely and delete all terraform execution within xpanse runtime. 
So its fine even if you can think of any temporary/manual solution to start the xpanse runtime to use terraform-boot for deployment

2023-08-24 09:21 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/deployers/terraform/request/TerraformDeployRequest.java
> +@Data
i dont think we need these data classes

2023-08-30 09:28 UTC, WangLiNaruto commented
> i'm a little confused now. Where are we exactly using the client which YangYang generated in this?

This is the code that generates the terraform-boot client. I have not yet submitted the code used in the terraform-boot client code. I will submit that code after waiting for the PR to be merged.

2023-08-31 06:53 UTC, swaroopar approved these changes
LGTM

2023-08-31 06:53 UTC, merged