add purge API method
eclipse-xpanse/xpanse pull request #808
Opened 2023-08-28 09:51 UTC by jinyangyang222

fixes #788

2023-08-28 12:29 UTC, jinyangyang222 commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> +        if (serviceDeploymentState == ServiceDeploymentState.DEPLOY_FAILED
fixed

2023-08-28 17:57 UTC, swaroopar requested changes
comments added.

2023-08-28 17:57 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> +                    String.format("Service with ID %s is not in a state requiring purging.",
pls change message to - Service %s is not in the state allowed for purging.

2023-08-28 17:57 UTC, swaroopar commented on modules/deployment/src/main/java/org/eclipse/xpanse/modules/deployment/DeployService.java
> +    public void purgeService(Deployment deployment, DeployTask deployTask) {
can you also please add tests for this? one for success case, one for rejection case.

2023-08-29 09:58 UTC, swaroopar approved these changes
LGTM

2023-08-29 09:58 UTC, merged